# Generated by Django 4.2.7 on 2023-12-20 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_date_ordered_alter_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 21, 32, 40, 947532)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 21, 32, 40, 947532)),
        ),
    ]
